### PR TITLE
Lesson 6 Pull request

### PR DESCRIPTION
**Pull request by eshans**
Here you go.

### CODE REVIEW

**Comment by gregdeane** [comment]
Thanks for opening the PR. It appears you are merging **from** master into `feature/step-6-routing` but it should be the other way around. Can you update?

Also, I don't see any mention of the `module.id` issue but maybe that's because of the reversed branches?

**Comment by eshans** [comment]
Weird. Sorry. I'll take a look

**Comment by eshans** [comment]
I have a few conflicts. Turned out the changes weren't committed before I
pushed the branch up. I'll resolve them.

**Comment by eshans** [comment]
Ok I created another PR correctly this time :). All conflicts have been
resolved

**Comment by eshans** [comment]
Btw - as far as the Module.Id thing, I've left it out of the project.

http://stackoverflow.com/questions/37178192/angular2-what-is-the-meanings-of-module-id-in-component

If you are using *webpack* for bundling then you don't need module.id in
decorator. Webpack plugins auto handle (add it) module.id in final bundle

It seems to break when I use it.

**Pull request merged**
