### PR TITLE
adding files for services

### PR DESCRIPTION
**Pull request by eshans**
Pull request for adding services. Hope I didn't screw it up!! :). I also had to debug something a while back -will clue you in but that's why there's a change in the package.json file - it had to do with typescript versioning and an error that kept happening..drove me nuts, ha. I wanted to try to solve it on my own, it seemed to bomb out when compiling ( the typescript loader). Alas..here you are.

### CODE REVIEW

**Comment by gregdeane** [comment]
@eshans Great work so far buddy. There are a couple of issues though...

1. This PR has merge conflicts so it appears that you didn't pull master before creating this branch. Please pull master, merge it into this branch, and fix all of the merge conflicts. Then commit and push this branch up again. At that point, I'll do the code review.

1. I pulled the `master` branch, installed packages, and ran the server. Both build and runtime errors were encountered. It might be related to the fix that you did in this branch. After this PR has been merged, please perform the following steps:

```bash
# in your project's root directory, run:
rm -rf node_modules  # careful with this command! :)

npm install

npm start

# make sure there are no build errors and make sure you can run the site without errors in the console.
```

**Comment by eshans** [comment]
Ok sure. I have all of the stuff on my other comp, so I'll get to it soon ( back to work today, boooooo)

**Comment by eshans** [comment]
Hey man, i'm gonna merge. I solved the conflicts. I think there was just some wonky with the commits or something. I didn't pull down master as I had been working from them for each branch. Anyhow - give it a look. I tested on my local and all is working ok.

**Comment by eshans** [comment]
I didn't run that test yet in the command line yet. I edited one of the node modules to fix that error - do you think it'll get overwritten by doing this? Sorry for the dumb question :)

**Comment by gregdeane** [comment]
Hey, sorry for the delayed response. I'm still getting a ton of errors and am unable to run the site locally on `master` branch. I have a suspicion that the reason it works for you is because you haven't reinstalled `node_modules` cleanly as I mentioned above (I could be wrong, however).

Some of the errors (but not all):
- `Uncaught ReferenceError: HEROES is not defined`
- `Argument of type '{ selector: string; template: string; import: { Hero: typeof Hero; }; from: string; const: any; H...' is not assignable to parameter of type 'Component'.`
- `':' expected.`
- `Property assignment expected.`

So you aren't seeing any errors/warnings in your terminal or Chrome console?

**Comment by gregdeane** [comment]
One issue is in [`app.component.ts`](https://github.com/eshans/ng2-tour-of-heroes/blob/master/src/app/app.component.ts). Note that `my-app` is being declared twice. This means that one of the previous merge conflicts was not resolved correctly.

Do you mind fixing this and any other errors? Do so one error at a time (then run the code and make sure everything works) so that it's easier to trace any problems.

Although it may break things for you, I suggest doing the `node_modules` clean-up as I suggested above. 

Thx man!

**Comment by eshans** [comment]
Ok,thanks - I'll take a look and install the clean up as you mentioned.

**Comment by eshans** [comment]
Hey man - I reinstalled my node modules but still works for me. This is quite strange :). What I want to do is just start the next chapter so I can just get familiar with it - in the meantime, perhaps you can take a look. I 'm not sure what's up. Sorry for screwing up that merge. Still a little new to all of this.

**Comment by gregdeane** [comment]
Opened PR #5 to fix these issues.

**Pull request merged**
