### PR TITLE
fix(app): remove duplicated component declarations

### PR DESCRIPTION
**Pull request by gregdeane**
Not sure how things are working for you but here are changes I implemented to make it work for me.  Pull this branch down and test this PR to make sure it still works as it should.

Be sure to delete `node_modules` and run `npm install` after pulling this branch down but **before** testing.

Thx!

### CODE REVIEW

**Comment by eshans** [comment]
thanks man, will do this now

**Comment by eshans** [comment]
Hey man, so I merged this and switched to my master branch. I also delete Node Modules and reinstalled. All seems ok

**Comment by eshans** [comment]
Tested and loaded the page with no errors

**Comment by gregdeane** [comment]
Great to hear man. Thanks!

**Comment by eshans** [comment]
Thank you :). I'll start on the next lesson

**Pull request merged**
